field: a96b2e64-4740-439e-9369-99916454625c # Recipe Contents
fieldLayouts:
  386da9f5-d669-495f-9dbf-96098707f09f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e136237d-a487-416e-aa74-d4fa73369dc4 # image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 254f83b6-4df8-43b9-be8e-fe100e748afe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8f345076-8263-472e-aef5-ea158decd144 # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dfe3cd9-6579-46fc-a819-8dc954e73c64
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6e0bc8d7-3161-43c0-a93f-81199bde3a77
        userCondition: null
fields:
  8f345076-8263-472e-aef5-ea158decd144: # Image Caption
    columnSuffix: yxydqzwh
    contentColumnType: text
    fieldGroup: null
    handle: imageCaption
    instructions: 'Enter the images caption'
    name: 'Image Caption'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e136237d-a487-416e-aa74-d4fa73369dc4: # image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'Insert image for recipe'
    name: image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:d9303b92-e6fd-4eb1-b8b8-7c38e959d869' # Drinks
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: 1
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:d9303b92-e6fd-4eb1-b8b8-7c38e959d869' # Drinks
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: recipeImage
name: 'Recipe Image'
sortOrder: 1
