columnSuffix: null
contentColumnType: string
fieldGroup: 7f51ed3d-1141-468c-80a6-b8ac334e239a # About
handle: drinkImages
instructions: null
name: 'Drink Images'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:d9303b92-e6fd-4eb1-b8b8-7c38e959d869' # Drinks
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:d9303b92-e6fd-4eb1-b8b8-7c38e959d869' # Drinks
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: 'Insert Image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:d9303b92-e6fd-4eb1-b8b8-7c38e959d869' # Drinks
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
